### ISSUE TITLE
Bedtime not working properly on Huawei, Xiaomi and similar custom OSs

### ISSUE THREAD

**Issue by nolhananas** [akaMrNagar/Mindful#72]
**Have you checked it on [Project Progress]() ?**
I have.

**Describe the bug**
Mindful often doesn't block websites after the designated hour as it should as per the bedtime feature. It also doesn't block listed websites.
It sometimes works, but quite rarely

**To Reproduce**
The bug is difficultly replicable in a repeatable manner.

**Additional context**
The problem seems to have sparked from a moment where the blocker worked too well and the "Close app" window didn't close.

I also tried reinstalling Mindful from the apk, which didn't work.

I also enabled all of the recommended settings (e.g Ignore battery optimization, Accessibility features...)

**Log file**
[Mindful-Logs-202534-23565.json](https://github.com/user-attachments/files/19078716/Mindful-Logs-202534-23565.json)

**Comment by nolhananas** [comment]
Thank you for your time! When it worked for a brief amount of time, it was great software.

**Comment by akaMrNagar** [comment]
Logs shows a crash when starting service during bedtime. I will take a look at it. But for now consider joining BETA or download PREVIEW from github as most of the issues have been fixed.

**Comment by nolhananas** [comment]
Thank you, will do.

**Comment by nolhananas** [comment]
Update on the issue: 
I updated to the latest beta: crashes do not show up in the logs anymore.
The Bedtime function still doesn't work, but I think I may have a lead on the issue: if the app enters naturally in the set schedule, it works properly. If, however, I turn on the bedtime schedule **while** being inside of the schedule, the function doesn't work.
It is as if Mindful doesn't detect that the schedule has started if it's turned on during that time.
I hope that helps!

**Comment by Gabbar-v7** [comment]
@nolhananas one thing that u can do is turn of the internet of any 1 app which will create a local vpn which will block its internet access. And since the vpn is maintained by the app os won't be able to put it to sleep. 
Which should cause the app to be awake and block insta, nfsw etc always. This works for try it. And also check if ur timer is set to 0 else ull have access to insta and stuff until then but nfsw will be blocked.

**Comment by akaMrNagar** [comment]
I think the problem is with the start and end time of bedtime head over to this thread for more info


https://github.com/akaMrNagar/Mindful/issues/40#issuecomment-2628241699

**Comment by nolhananas** [comment]
@akaMrNagar I don't think so, as I was careful to put the start before 12AM and the end after.
However, I saw in the linked thread that these kind of issue happen more frequently ô Huawei and Xiaomi devices. It so happens that my phone is a Honor running on magic OS, which used to be developed by Huawei.
Maybe this is solely an issue related to the way the os manages processes.
Thanks for your time anyhow!

![Image](https://github.com/user-attachments/assets/d7bcc880-a2e2-4181-9536-63baf6f349f3)

**Comment by akaMrNagar** [comment]
The screenshot shows that the start of bedtime is 22  which is 10pm and the end time is 6 which is 6am so you are starting today and stopping tomorrow which is fine abd it should work. 


Is it not working on next day too? 
PS: I need more info to fix this issue. Check alarms and reminders permission along with ignore battery optimization and check if your device have any security center and whitelist Mindful there.

**Comment by nolhananas** [comment]
> Is it not working on next day too?

Unfortunately no, as you can see in this recording, it is currently 1 AM and duckduckgo opens even though it shouldn't.
https://github.com/user-attachments/assets/31bd5ec6-c311-4bda-8146-334a2955a964

> PS: I need more info to fix this issue. Check alarms and reminders permission along with ignore battery optimization and check if your device have any security center and whitelist Mindful there.

I whitelisted mindful everywhere I could, that is:
- I disabled battery optimisation to allow mindful to run in the background 
- I granted mindful accessibility permissions
- Mindful is allowed to send notifications
- I allowed mindful to appear on top of other apps

If that can help, here are some system info about my system.

![Image](https://github.com/user-attachments/assets/0d09b2cb-9493-427e-87f3-d07b811b1c23)
![Image](https://github.com/user-attachments/assets/f3bff775-5012-4ad4-a99f-da301cf6cc20)

Here are mindful's services that are currently running

![Image](https://github.com/user-attachments/assets/b59b437a-632c-4990-9bb9-1630a44d164b)

**Comment by akaMrNagar** [comment]
That's odd🤔 beside all the permissions it's not working. Did you get any notification 30 minutes prior the bedtime? or when you enable the schedule when you are between the start and end time ?

**Comment by nolhananas** [comment]
I got a notification 30 minutes before indeed, but no notification when it should have started.

Apps also get blocked outside the bedtime schedule sometimes.

**Comment by akaMrNagar** [comment]
Do you have any other restrictions set for apps or groups?

**Comment by nolhananas** [comment]
I don't have any other restrictions in place

**Comment by akaMrNagar** [comment]
Tried reinstalling?

**Comment by nolhananas** [comment]
I tried installing the beta instead of stable as you suggested earlier, so I had to reinstall the app. I could try doing it again if that helps

**Comment by akaMrNagar** [comment]
Can't find the reason behind the issue. Start bedtime just 5 minutes later and then check the running services and let me know. On more thing make sure all notification channels are enabled in notifications settings.


If you see another service named MindfulTrackingService, let me know...

**Comment by nolhananas** [comment]
I am happy to report that bedtime has been working flawlessly for the past few days.
Only bad news is that I don't really know what I changed to make it work.
I'll keep you posted if I have any clue, as always.
